
  //1 script
var et_site_url='https://metrohomebuilders.com';var et_post_id='22';function et_core_page_resource_fallback(a,b){"undefined"===typeof b&&(b=a.sheet.cssRules&&0===a.sheet.cssRules.length);b&&(a.onerror=null,a.onload=null,a.href?a.href=et_site_url+"/?et_core_page_resource="+a.id+et_post_id:a.src&&(a.src=et_site_url+"/?et_core_page_resource="+a.id+et_post_id))}

  //2 script
{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://metrohomebuilders.com/#organization","name":"Metro Home Builders","url":"https://secureservercdn.net/198.71.233.109/l7a.aa9.myftpupload.com/","sameAs":["https://www.facebook.com/metrohomebuilders/","https://www.instagram.com/metrohomesnaples/"],"logo":{"@type":"ImageObject","@id":"https://metrohomebuilders.com/#logo","inLanguage":"en-US","url":"https://secureservercdn.net/198.71.233.109/l7a.aa9.myftpupload.com/wp-content/uploads/2019/11/logo.png?time=1643683861","contentUrl":"https://secureservercdn.net/198.71.233.109/l7a.aa9.myftpupload.com/wp-content/uploads/2019/11/logo.png?time=1643683861","width":283,"height":78,"caption":"Metro Home Builders"},"image":{"@id":"https://metrohomebuilders.com/#logo"}},{"@type":"WebSite","@id":"https://metrohomebuilders.com/#website","url":"https://metrohomebuilders.com/","name":"Metro Home Builders, Inc","description":"Building is our business... Service is our asset!","publisher":{"@id":"https://metrohomebuilders.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://metrohomebuilders.com/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"WebPage","@id":"https://metrohomebuilders.com/contact-us/#webpage","url":"https://metrohomebuilders.com/contact-us/","name":"Contact Us - Metro Home Builders, Inc","isPartOf":{"@id":"https://metrohomebuilders.com/#website"},"datePublished":"2019-11-20T01:54:26+00:00","dateModified":"2020-08-28T19:44:19+00:00","description":"Metro Home Builders, Inc in Naples, FL has a team of custom home construction experts dedicated to meeting your needs. When doing business with you, we pay the utmost attention to your needs to ensure that we can exceed your expectations. Learn more about our company by reaching out to us.","breadcrumb":{"@id":"https://metrohomebuilders.com/contact-us/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://metrohomebuilders.com/contact-us/"]}]},{"@type":"BreadcrumbList","@id":"https://metrohomebuilders.com/contact-us/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://metrohomebuilders.com/"},{"@type":"ListItem","position":2,"name":"Contact Us"}]}]}
  //3 script

window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.1.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/secureservercdn.net\/198.71.233.109\/l7a.aa9.myftpupload.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.9&time=1644336645"}};
/*! This file is auto-generated */
!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){var a=String.fromCharCode;p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,e),0,0);e=i.toDataURL();return p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,t),0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(!p||!p.fillText)return!1;switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])?!1:!s([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!s([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]);case"emoji":return!s([10084,65039,8205,55357,56613],[10084,65039,8203,55357,56613])}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],"flag"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(n=t.source||{}).concatemoji?c(n.concatemoji):n.wpemoji&&n.twemoji&&(c(n.twemoji),c(n.wpemoji)))}(window,document,window._wpemojiSettings);

  //4 script

var et_core_api_spam_recaptcha = {"site_key":"","page_action":{"action":"contact_us"}};

  //5 script

			var bb_powerpack = {
				ajaxurl: 'https://metrohomebuilders.com/wp-admin/admin-ajax.php'
			};
		
  //6 script

			document.documentElement.className = document.documentElement.className.replace( 'no-js', 'js' );
		
  //7 script
jQuery(document).ready(function($){gformInitSpinner( 1, 'https://secureservercdn.net/198.71.233.109/l7a.aa9.myftpupload.com/wp-content/plugins/gravityforms/images/spinner.gif' );jQuery('#gform_ajax_frame_1').on('load',function(){var contents = jQuery(this).contents().find('*').html();var is_postback = contents.indexOf('GF_AJAX_POSTBACK') >= 0;if(!is_postback){return;}var form_content = jQuery(this).contents().find('#gform_wrapper_1');var is_confirmation = jQuery(this).contents().find('#gform_confirmation_wrapper_1').length > 0;var is_redirect = contents.indexOf('gformRedirect(){') >= 0;var is_form = form_content.length > 0 && ! is_redirect && ! is_confirmation;var mt = parseInt(jQuery('html').css('margin-top'), 10) + parseInt(jQuery('body').css('margin-top'), 10) + 100;if(is_form){jQuery('#gform_wrapper_1').html(form_content.html());if(form_content.hasClass('gform_validation_error')){jQuery('#gform_wrapper_1').addClass('gform_validation_error');} else {jQuery('#gform_wrapper_1').removeClass('gform_validation_error');}setTimeout( function() { /* delay the scroll by 50 milliseconds to fix a bug in chrome */ jQuery(document).scrollTop(jQuery('#gform_wrapper_1').offset().top - mt); }, 50 );if(window['gformInitDatepicker']) {gformInitDatepicker();}if(window['gformInitPriceFields']) {gformInitPriceFields();}var current_page = jQuery('#gform_source_page_number_1').val();gformInitSpinner( 1, 'https://secureservercdn.net/198.71.233.109/l7a.aa9.myftpupload.com/wp-content/plugins/gravityforms/images/spinner.gif' );jQuery(document).trigger('gform_page_loaded', [1, current_page]);window['gf_submitting_1'] = false;}else if(!is_redirect){var confirmation_content = jQuery(this).contents().find('.GF_AJAX_POSTBACK').html();if(!confirmation_content){confirmation_content = contents;}setTimeout(function(){jQuery('#gform_wrapper_1').replaceWith(confirmation_content);jQuery(document).scrollTop(jQuery('#gf_1').offset().top - mt);jQuery(document).trigger('gform_confirmation_loaded', [1]);window['gf_submitting_1'] = false;}, 50);}else{jQuery('#gform_1').append(contents);if(window['gformRedirect']) {gformRedirect();}}jQuery(document).trigger('gform_post_render', [1, current_page]);} );} );
  //8 script
 jQuery(document).bind('gform_post_render', function(event, formId, currentPage){if(formId == 1) {} } );jQuery(document).bind('gform_post_conditional_logic', function(event, formId, fields, isInit){} );
  //9 script
 jQuery(document).ready(function(){jQuery(document).trigger('gform_post_render', [1, 1]) } ); 
  //10 script

var et_pb_custom = {"ajaxurl":"https:\/\/metrohomebuilders.com\/wp-admin\/admin-ajax.php","images_uri":"https:\/\/metrohomebuilders.com\/wp-content\/themes\/bb-theme\/images","builder_images_uri":"https:\/\/metrohomebuilders.com\/wp-content\/plugins\/divi-builder\/includes\/builder\/images","et_frontend_nonce":"3fe9bcb7ac","subscription_failed":"Please, check the fields below to make sure you entered the correct information.","et_ab_log_nonce":"d99c09cd9b","fill_message":"Please, fill in the following fields:","contact_error_message":"Please, fix the following errors:","invalid":"Invalid email","captcha":"Captcha","prev":"Prev","previous":"Previous","next":"Next","wrong_captcha":"You entered the wrong number in captcha.","wrong_checkbox":"Checkbox","ignore_waypoints":"no","is_divi_theme_used":"","widget_search_selector":".widget_search","ab_tests":[],"is_ab_testing_active":"","page_id":"22","unique_test_id":"","ab_bounce_rate":"5","is_cache_plugin_active":"yes","is_shortcode_tracking":"","tinymce_uri":""}; var et_builder_utils_params = {"condition":{"diviTheme":false,"extraTheme":false},"scrollLocations":["app","top"],"builderScrollLocations":{"desktop":"app","tablet":"app","phone":"app"},"onloadScrollLocation":"app","builderType":"fe"}; var et_frontend_scripts = {"builderCssContainerPrefix":"#et-boc","builderCssLayoutPrefix":"#et-boc .et-l"};
var et_pb_box_shadow_elements = [];
var et_pb_motion_elements = {"desktop":[],"tablet":[],"phone":[]};
var et_pb_sticky_elements = [];

  //11 script

var themeopts = {"medium_breakpoint":"992","mobile_breakpoint":"768"};

  //12 script

var gf_global = {"gf_currency_config":{"name":"U.S. Dollar","symbol_left":"$","symbol_right":"","symbol_padding":"","thousand_separator":",","decimal_separator":".","decimals":2},"base_url":"https:\/\/metrohomebuilders.com\/wp-content\/plugins\/gravityforms","number_formats":[],"spinnerUrl":"https:\/\/metrohomebuilders.com\/wp-content\/plugins\/gravityforms\/images\/spinner.gif"};
var gf_global = {"gf_currency_config":{"name":"U.S. Dollar","symbol_left":"$","symbol_right":"","symbol_padding":"","thousand_separator":",","decimal_separator":".","decimals":2},"base_url":"https:\/\/metrohomebuilders.com\/wp-content\/plugins\/gravityforms","number_formats":[],"spinnerUrl":"https:\/\/metrohomebuilders.com\/wp-content\/plugins\/gravityforms\/images\/spinner.gif"};

  //13 script
'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'wpaas'},{'server':'1ee82ad5-a975-208c-136a-23f9a9cce72c.secureserver.net'},{'pod':'A2NLWPPOD06'},{'storage':'a2pewpnas02_data02'},{'xid':'42938785'},{'wp':'5.9'},{'php':'7.2.34'},{'loggedin':'0'},{'cdn':'1'},{'builder':'beaver-builder'},{'theme':'bb-theme'},{'nextgen':'0'},{'wds':'1'},{'wp_alloptions_count':'278'},{'wp_alloptions_bytes':'137918'})
  //14 script
window.addEventListener('click', function (elem) { var _elem$target, _elem$target$dataset, _window, _window$_trfq; return (elem === null || elem === void 0 ? void 0 : (_elem$target = elem.target) === null || _elem$target === void 0 ? void 0 : (_elem$target$dataset = _elem$target.dataset) === null || _elem$target$dataset === void 0 ? void 0 : _elem$target$dataset.eid) && ((_window = window) === null || _window === void 0 ? void 0 : (_window$_trfq = _window._trfq) === null || _window$_trfq === void 0 ? void 0 : _window$_trfq.push(["cmdLogEvent", "click", elem.target.dataset.eid]));});